### ISSUE TITLE
Fix the Console

### ISSUE THREAD

**Issue by ttanatb** [engine-buddies/light-vox-engine#12]
**Describe the bug**
The console doesn't work

**To Reproduce**
try to std::cout or printf

**Expected behavior**
Something should appear

**Comment by RMichelsen** [comment]
Hi, I've tried reproducing the issue but I can't. If I call printf from either `Engine::Run()` or `Engine::CreateConsoleWindow()` I do get output as expected.

**Comment by BenjaFriend** [comment]
Closing this issue because you can receive output from the console.
