### ISSUE TITLE
Memory Leaks from DX12 Resources

### ISSUE THREAD

**Issue by BenjaFriend** [engine-buddies/light-vox-engine#13]
**Describe the bug**
There are a lot of memory leaks with the DX12 resources! 

**To Reproduce**
1 Start the program, and hit the red X to close the window
2. See the `Output` window in Visual Studio

**Expected behavior**
A bunch of memory leaks in the output that will show up from the DirectX12 resources not being cleaned up

**Build Configuration (please complete the following information):**
 - Debug and Release
 - x32 and x64

**Comment by ttanatb** [comment]
Fixed in https://github.com/engine-buddies/light-vox-engine/pull/10
