### ISSUE TITLE
Cleanup: Re-organize files

### ISSUE THREAD

**Issue by ttanatb** [engine-buddies/light-vox-engine#20]
Ben wants organization (after release is cut)

**Comment by BenjaFriend** [comment]
Meaning to add some better folder structure to the environment, like separating the different systems into their own folders. As well as using namespaces for the different subsystem to make for a more explicit dev environment and better type safety

- [x] Namespaces
- [x] Folder Structure

**Comment by BenjaFriend** [comment]
Complete!
