### ISSUE TITLE
Unit Testing Framework

### ISSUE THREAD

**Issue by BenjaFriend** [engine-buddies/light-vox-engine#23]
**Is your feature request related to a problem? Please describe.**

No, it is going to be a Unit Testing framework for our core physics and data structure functionality so that we can test our code. 

**Describe the solution you'd like**

A new `vcxproj` for unit testing inside the engine's solution, with examples of how to add unit testing to our code!

**Describe alternatives you've considered**

Considered Google Test, but the native Unit testing in Visual C++ is probably going to be the easiest and introduce less dependencies than using another toolkit/library

**Comment by ttanatb** [comment]
Fixed in https://github.com/engine-buddies/light-vox-engine/pull/25
