### ISSUE TITLE
Cross Platform: Refs vs Moves 

### ISSUE THREAD

**Issue by ttanatb** [engine-buddies/light-vox-engine#55]
Some function call passes in temporary variables as a reference (rhs vs lhs) and I guess Clang doesn't like that. The error came from RigidBody

Example:
`        void Velocity(glm::vec3& vel, const size_t& index);`
`                rigidBody->Velocity(glm::vec3(10.0f, 0.0f, 0.0f), entityID);`
this will throw an error

`        void Velocity(glm::vec3&& vel, const size_t& index);`
`                rigidBody->Velocity(glm::vec3(10.0f, 0.0f, 0.0f), entityID);`
this won't throw an error

**Comment by BenjaFriend** [comment]
This has  been fixed, the project compiles with clang!
